#!/bin/bash

#SBATCH --job-name=single_Pacbio      ## Name of the job.
#SBATCH -A grylee_lab     ## account to charge
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=5    ## number of cores the job needs max 64
#SBATCH --error=slurm-%J.err ## error log file
#SBATCH -t 5-20:00:00

module load repeatmasker
RepeatMasker -q GCF_017639315.1_ASM1763931v2_genomic.fna -species drosophila -e hmmer

