#!/bin/bash

#SBATCH --job-name=single_Illumina      ## Name of the job.
#SBATCH -A grylee_lab     ## account to charge
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=6    ## number of cores the job needs
#SBATCH --error=slurm-%J.err ## error log file
#SBATCH -t 4-20:00:00

module load bwa/0.7.17
module load samtools/1.15.1
module load minimap2
module load repeatmasker

id=San #change for different species
r1="${id}-READ1-Sequences.txt"
r2="${id}-READ2-Sequences.txt"
trim_galore --pair raw_reads/${r1} raw_reads/${r2} --fastqc --illumina

reads_1="/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/usftp21.novogene.com/raw_data/${id}/${id}_val_1.fq"
reads_2="/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/usftp21.novogene.com/raw_data/${id}/${id}_val_2.fq"

## for estimating satellite repeat abundance
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/bin/kmc -fq -k21 -t6 -ci100 -cs100000 ${reads_1} count1.kmc tmp_dir
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/bin/kmc -fq -k21 -t6 -ci100 -cs100000 ${reads_2} count2.kmc tmp_dir
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/bin/kmc_tools simple count1.kmc count2.kmc union kmc_${id}
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/bin/kmc_tools transform kmc_${id} dump kmc_${id}.txt
#/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/bin/kmc_dump count1.kmc count.txt
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/srf/srf -p prefix kmc_${id}.txt > ${id}_srf.fa
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/srf/srfutils.js enlong ${id}_srf.fa > ${id}_srf.enlong.fa
minimap2 -c -x sr -N1000000 -f1000 -r100,100 -t6 ${id}_srf.enlong.fa ${reads_1} ${reads_2} > ${id}_srf.paf
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/srf/srfutils.js paf2bed -l 20 ${id}_srf.paf > ${id}_srf.bed
/dfs7/grylee/yuhenh3/Heterochromatic_repeat_Novagenes_17species/srf/srfutils.js bed2abun ${id}_srf.bed > ${id}_srf.abun
