#!/bin/bash
#SBATCH --job-name=coevol
#SBATCH -A grylee_lab
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=1G
#SBATCH --time=12:00:00
#SBATCH --error=%x.%A.err
#SBATCH --out=%x.%A.out


#run commands

#/dfs7/grylee/grylee/coevol/Coevol/coevol-master/data/coevol -d X_codon -t coevol_tree_file.txt -c dro.traits_4.txt -dsom X_run1
/dfs7/grylee/grylee/coevol/Coevol/coevol-master/data/coevol -d X_codon -t coevol_tree_file.txt -c dro.traits_4.txt -dsom X_run2
#/dfs7/grylee/grylee/coevol/Coevol/coevol-master/data/tracecomp -x 100 X_run1 X_run2
#/dfs7/grylee/grylee/coevol/Coevol/coevol-master/data/readcoevol -x 300 X_run1